# configure language supprot and functions
CONFIG_CPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_REQUIRES_FULL_LIBC=y
CONFIG_STD_CPP20=y

# Enable the TWI (I2C) driver
CONFIG_I2C=y

# Enable logging (optional, useful for debugging)
CONFIG_LOG=y

# configure logging via rtt
CONFIG_LOG=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_PRINTK=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_UART=n


# configure available time functions
CONFIG_MINIMAL_LIBC_TIME=y
CONFIG_POSIX_CLOCK=y