# Enable the TWI (I2C) driver
CONFIG_I2C=y

# Enable logging (optional, useful for debugging)
CONFIG_LOG=y
# Set log level (0-4, where 4 is the most verbose)
CONFIG_LOG_DEFAULT_LEVEL=3


# configure logging via rtt
CONFIG_LOG=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_PRINTK=y
CONFIG_USE_SEGGER_RTT=y