# configure language supprot and functions
CONFIG_CPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_REQUIRES_FULL_LIBC=y
CONFIG_STD_CPP20=y

CONFIG_SERIAL=y

# configuring uart
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_USE_RUNTIME_CONFIGURE=y

# enable uart for measuring power consumption and waking modules up
CONFIG_GPIO=y
CONFIG_PM_DEVICE=y=y

# we enable poll for working with uart
# this allows for efficient use of message queues
CONFIG_POLL=y

# configure the default stack size
# wee store most data on the stack
CONFIG_MAIN_STACK_SIZE=4096

# configure available time functions
CONFIG_MINIMAL_LIBC_TIME=y
CONFIG_POSIX_CLOCK=y


# configure logging via rtt
CONFIG_LOG=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_PRINTK=y
CONFIG_USE_SEGGER_RTT=y