timeline
    30.10.2024  : Blinking LED
                : [SENSORS] Analog Input
    04.11.2024  : [UART] Simple UART Communication
                : [SIM7000E] Getting familiar with AT commands
    10.11.2024  : [CLOUD_SERVICE] Azure function for adding data to MongoDB
                : [UART] UART Abstraction
                : [SIM7000E] Interactive HTTP requests
    16.11.2024  : [SIM7000E] Interactive HTTPS requests
                : [SIM7000E] AT command API for HTTP/HTTPS requests
    17.11.2024  : [SIM7000E] Time synchronization via AT commands
    18.11.2024  : [RYLR498] Working LoRa P2P communication
                : [IIC] I2C communication in Zephyr
                : [RTC] Real-Time Clock read and decode
                : [SIM7000E] TLS working programatically
    02.12.2024  : [RYLR498] API for LoRa P2P communication, setting power...
                : [IIC] Driver Abstraction
                : [RTC] RTC Abstraction
                : [SENSORS] Moisture sensor implementation
                : [BATTERY] Battery level monitoring
    05.12.2024  : [SIM7000E] Low Power Mode
                : [IIC] Sample project for driver usage
    06.12.2024  : [SIM7000E] Set time by RTC
    09.12.2024  : [RYLR498] Implemeneted Simple LoRa Gateway
                : [RTC] Implementation using Zephyr drivers
    12.12.2024  : [RYLR498] Sending moisture data periodically
                : [RTC] Alarm implementation
                : [POWER] Power management using sleep and poweroff
    16.12.2024  : [RTC] Alarm triggering watchdog pin every minute
    28.12.2024  : [SIM7000E] Power off / wake-up
    02.01.2025  : [UART] UART-Suspend/Resume and power comsumption measurements
                : [CLOUD_SERVICE] Change Response to current time
    03.01.2025  : [GATEWAY] Gateway implementation with SIM7000E, DS1307, RYLR498, moisture sensor and battery monitoring
    04.01.2025  : [GATEWAY] Data Collection Thread
    10.01.2025  : [NODE] Deep sleep, wake-up on RTC alarm, UART-Driver update
                : [GATEWAY] Functionallity complete
    11.01.2025  : [BEAUTIFY] Building casing for gateway and nodes
                : [GATEWAY] Power consumption measurements
                : [BATTERY] Battery circuit design
    13.01.2025  : [GATEWAY] Design and soldering of the PCB
                : [NODE] Design and soldering of the PCB
                : [GATEWAY] External Power Supply
